apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: coforge-idp-service
  description: First Service for the POC of Coforge-IDP
  annotations:
    backstage.io/techdocs-ref: dir:.
    harness.io/workspace-url: |
      labelA: https://app.harness.io/ng/account/8Xl8tQSaSeyvtccXETil_Q/module/iacm/orgs/CoforgeCIMSPE/projects/CoforgeIDPPE/workspaces/CoforgeIDPPE/resources
  tags:
    - java
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: production
  owner: Manas Shukla
  system: project-coforge-idp
