site_name: 'Coforge-IDP-PE Documentation'
repo_url: https://github.com/manasshuklacoforge/Coforge-IDP-PE
edit_uri: https://github.com/manasshuklacoforge/Coforge-IDP-PE/blob/main/docs/index.md
nav:
  - Home: index.md

plugins:
  - techdocs-core
